/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FarmRecord = IDL.Record({
  'latitude' : IDL.Float64,
  'createdAt' : IDL.Int,
  'corporateName' : IDL.Text,
  'adminArea' : IDL.Text,
  'longitude' : IDL.Float64,
  'grade' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'commodity' : IDL.Text,
  'farmerName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScanEvent = IDL.Record({
  'timestamp' : IDL.Int,
  'deviceType' : IDL.Text,
  'userAgent' : IDL.Text,
  'farmId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'organization' : IDL.Text,
});
export const ScanStats = IDL.Record({
  'scanEvents' : IDL.Vec(ScanEvent),
  'totalScans' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFarmRecord' : IDL.Func([IDL.Text, FarmRecord], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllFarmRecords' : IDL.Func([], [IDL.Vec(FarmRecord)], ['query']),
  'getAllScanStats' : IDL.Func([], [IDL.Vec(ScanEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFarmRecord' : IDL.Func([IDL.Text], [FarmRecord], ['query']),
  'getFarmScanStats' : IDL.Func([IDL.Text], [ScanStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logScan' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FarmRecord = IDL.Record({
    'latitude' : IDL.Float64,
    'createdAt' : IDL.Int,
    'corporateName' : IDL.Text,
    'adminArea' : IDL.Text,
    'longitude' : IDL.Float64,
    'grade' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'commodity' : IDL.Text,
    'farmerName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScanEvent = IDL.Record({
    'timestamp' : IDL.Int,
    'deviceType' : IDL.Text,
    'userAgent' : IDL.Text,
    'farmId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'organization' : IDL.Text,
  });
  const ScanStats = IDL.Record({
    'scanEvents' : IDL.Vec(ScanEvent),
    'totalScans' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFarmRecord' : IDL.Func([IDL.Text, FarmRecord], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllFarmRecords' : IDL.Func([], [IDL.Vec(FarmRecord)], ['query']),
    'getAllScanStats' : IDL.Func([], [IDL.Vec(ScanEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFarmRecord' : IDL.Func([IDL.Text], [FarmRecord], ['query']),
    'getFarmScanStats' : IDL.Func([IDL.Text], [ScanStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logScan' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };