/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FarmRecord {
  'latitude' : number,
  'createdAt' : bigint,
  'corporateName' : string,
  'adminArea' : string,
  'longitude' : number,
  'grade' : string,
  'phoneNumber' : string,
  'commodity' : string,
  'farmerName' : string,
  'varieties' : [] | [string],
  'farmSize' : [] | [string],
  'coffeeTreeCount' : [] | [string],
  'shadeTreePct' : [] | [string],
}
export interface ScanEvent {
  'timestamp' : bigint,
  'deviceType' : string,
  'userAgent' : string,
  'farmId' : string,
}
export interface ScanStats {
  'scanEvents' : Array<ScanEvent>,
  'totalScans' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'organization' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFarmRecord' : ActorMethod<[string, FarmRecord], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllFarmRecords' : ActorMethod<[], Array<FarmRecord>>,
  'getAllScanStats' : ActorMethod<[], Array<ScanEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFarmRecord' : ActorMethod<[string], FarmRecord>,
  'getFarmScanStats' : ActorMethod<[string], ScanStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logScan' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
